package htw.gma_sose22.metronomekit.metronome

import htw.gma_sose22.metronomekit.audio.AudioWriteable
import htw.gma_sose22.metronomekit.audio.StatelessAudioControllable

interface MetronomeAudioInterface : AudioWriteable, StatelessAudioControllable